name: CI/CD Pipeline

on:
  push:
    branches: main

# jobs:
#   deploy:
#     runs-on: self-hosted

#     env:
#       IMAGE_NAME: pixer-app
#       IMAGE_TAG: latest
#       REGISTRY: docker.io

#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v4

#       - name: Run Trivy vulnerability scan
#         run: |
#           trivy image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY/$IMAGE_NAME:$IMAGE_TAG || true

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build Docker image
#         run: |
#           docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .

#       - name: Push Docker image
#         run: |
#           docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

#       - name: Stop and remove old container (if running)
#         run: |
#           if [ "$(docker ps -q)" ]; then
#               docker stop $(docker ps -q)
#           else
#               echo "No running containers to stop."
#           fi

#           # if [ "$(docker images -q)" ]; then
#           #   docker rmi $(docker images -q)
#           # else
#           #     echo "No images to remove."
#           # fi


          

        

#       - name: Run new container
#         run: |
#           docker run -d --name $IMAGE_NAME -p 5000:80 $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG




jobs:
  deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: pixer-app
      IMAGE_TAG: latest
      REGISTRY: docker.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
    
    steps:
      - name: Install Trivy
        run: |
            sudo apt-get update
            sudo apt-get install wget apt-transport-https gnupg lsb-release -y
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy -y

      - name: Run Trivy vulnerability scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY/$IMAGE_NAME:$IMAGE_TAG || true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Stop and remove old container (if exists)
        run: |
          if [ "$(docker ps -q -f name=$IMAGE_NAME)" ]; then
              docker stop $IMAGE_NAME
          else
              echo "No running container named $IMAGE_NAME to stop."
          fi

          if [ "$(docker ps -aq -f name=$IMAGE_NAME)" ]; then
              docker rm $IMAGE_NAME
          else
              echo "No container named $IMAGE_NAME to remove."
          fi

      - name: Run new container
        run: |
          docker run -d --name $IMAGE_NAME -p 5000:80 $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
